# Generated by Django 2.1.7 on 2019-03-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_auto_20190327_0723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fields',
            new_name='Field',
        ),
    ]
