# Generated by Django 2.1.7 on 2019-03-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_auto_20190327_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('icon', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=150)),
            ],
        ),
    ]
