# Generated by Django 2.1.7 on 2019-03-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
