# Generated by Django 2.1.7 on 2019-03-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_auto_20190327_0911'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
