# Generated by Django 2.1.7 on 2019-03-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0008_auto_20190327_0911'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Field',
            new_name='Section',
        ),
    ]
